/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Model");
		private final Assignment cLibrariesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLibrariesLibraryParserRuleCall_0 = (RuleCall)cLibrariesAssignment.eContents().get(0);
		
		//Model:
		//    libraries+=Library*;
		@Override public ParserRule getRule() { return rule; }
		
		//libraries+=Library*
		public Assignment getLibrariesAssignment() { return cLibrariesAssignment; }
		
		//Library
		public RuleCall getLibrariesLibraryParserRuleCall_0() { return cLibrariesLibraryParserRuleCall_0; }
	}
	public class LibraryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Library");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLibraryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUsersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUsersUserParserRuleCall_3_0 = (RuleCall)cUsersAssignment_3.eContents().get(0);
		private final Assignment cBooksAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBooksBookParserRuleCall_4_0 = (RuleCall)cBooksAssignment_4.eContents().get(0);
		private final Assignment cReservationsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cReservationsReservationParserRuleCall_5_0 = (RuleCall)cReservationsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Library:
		//    'library' name=ID '{'
		//        users+=User*
		//        books+=Book*
		//        reservations+=Reservation*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'library' name=ID '{'
		//    users+=User*
		//    books+=Book*
		//    reservations+=Reservation*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'library'
		public Keyword getLibraryKeyword_0() { return cLibraryKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//users+=User*
		public Assignment getUsersAssignment_3() { return cUsersAssignment_3; }
		
		//User
		public RuleCall getUsersUserParserRuleCall_3_0() { return cUsersUserParserRuleCall_3_0; }
		
		//books+=Book*
		public Assignment getBooksAssignment_4() { return cBooksAssignment_4; }
		
		//Book
		public RuleCall getBooksBookParserRuleCall_4_0() { return cBooksBookParserRuleCall_4_0; }
		
		//reservations+=Reservation*
		public Assignment getReservationsAssignment_5() { return cReservationsAssignment_5; }
		
		//Reservation
		public RuleCall getReservationsReservationParserRuleCall_5_0() { return cReservationsReservationParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class UserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.User");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUserKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEmailKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEmailAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEmailSTRINGTerminalRuleCall_3_0 = (RuleCall)cEmailAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBooksKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOwnedBooksAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cOwnedBooksBookCrossReference_4_2_0 = (CrossReference)cOwnedBooksAssignment_4_2.eContents().get(0);
		private final RuleCall cOwnedBooksBookIDTerminalRuleCall_4_2_0_1 = (RuleCall)cOwnedBooksBookCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOwnedBooksAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cOwnedBooksBookCrossReference_4_3_1_0 = (CrossReference)cOwnedBooksAssignment_4_3_1.eContents().get(0);
		private final RuleCall cOwnedBooksBookIDTerminalRuleCall_4_3_1_0_1 = (RuleCall)cOwnedBooksBookCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCurrentReservationKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCurrentReservationAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cCurrentReservationReservationCrossReference_5_1_0 = (CrossReference)cCurrentReservationAssignment_5_1.eContents().get(0);
		private final RuleCall cCurrentReservationReservationIDTerminalRuleCall_5_1_0_1 = (RuleCall)cCurrentReservationReservationCrossReference_5_1_0.eContents().get(1);
		
		//User:
		//    'user' name=ID 'email=' email=STRING
		//    ('books=' '{' ownedBooks+=[Book] (',' ownedBooks+=[Book])* '}')?
		//    ('currentReservation=' currentReservation=[Reservation])?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'user' name=ID 'email=' email=STRING
		//('books=' '{' ownedBooks+=[Book] (',' ownedBooks+=[Book])* '}')?
		//('currentReservation=' currentReservation=[Reservation])?
		public Group getGroup() { return cGroup; }
		
		//'user'
		public Keyword getUserKeyword_0() { return cUserKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'email='
		public Keyword getEmailKeyword_2() { return cEmailKeyword_2; }
		
		//email=STRING
		public Assignment getEmailAssignment_3() { return cEmailAssignment_3; }
		
		//STRING
		public RuleCall getEmailSTRINGTerminalRuleCall_3_0() { return cEmailSTRINGTerminalRuleCall_3_0; }
		
		//('books=' '{' ownedBooks+=[Book] (',' ownedBooks+=[Book])* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'books='
		public Keyword getBooksKeyword_4_0() { return cBooksKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//ownedBooks+=[Book]
		public Assignment getOwnedBooksAssignment_4_2() { return cOwnedBooksAssignment_4_2; }
		
		//[Book]
		public CrossReference getOwnedBooksBookCrossReference_4_2_0() { return cOwnedBooksBookCrossReference_4_2_0; }
		
		//ID
		public RuleCall getOwnedBooksBookIDTerminalRuleCall_4_2_0_1() { return cOwnedBooksBookIDTerminalRuleCall_4_2_0_1; }
		
		//(',' ownedBooks+=[Book])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//','
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//ownedBooks+=[Book]
		public Assignment getOwnedBooksAssignment_4_3_1() { return cOwnedBooksAssignment_4_3_1; }
		
		//[Book]
		public CrossReference getOwnedBooksBookCrossReference_4_3_1_0() { return cOwnedBooksBookCrossReference_4_3_1_0; }
		
		//ID
		public RuleCall getOwnedBooksBookIDTerminalRuleCall_4_3_1_0_1() { return cOwnedBooksBookIDTerminalRuleCall_4_3_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('currentReservation=' currentReservation=[Reservation])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'currentReservation='
		public Keyword getCurrentReservationKeyword_5_0() { return cCurrentReservationKeyword_5_0; }
		
		//currentReservation=[Reservation]
		public Assignment getCurrentReservationAssignment_5_1() { return cCurrentReservationAssignment_5_1; }
		
		//[Reservation]
		public CrossReference getCurrentReservationReservationCrossReference_5_1_0() { return cCurrentReservationReservationCrossReference_5_1_0; }
		
		//ID
		public RuleCall getCurrentReservationReservationIDTerminalRuleCall_5_1_0_1() { return cCurrentReservationReservationIDTerminalRuleCall_5_1_0_1; }
	}
	public class BookElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Book");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBookKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cAuthorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAuthorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAuthorSTRINGTerminalRuleCall_3_0 = (RuleCall)cAuthorAssignment_3.eContents().get(0);
		private final Keyword cIsbnKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cIsbnAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cIsbnSTRINGTerminalRuleCall_5_0 = (RuleCall)cIsbnAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cBorrowedByKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cBorrowerAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cBorrowerUserCrossReference_6_1_0 = (CrossReference)cBorrowerAssignment_6_1.eContents().get(0);
		private final RuleCall cBorrowerUserIDTerminalRuleCall_6_1_0_1 = (RuleCall)cBorrowerUserCrossReference_6_1_0.eContents().get(1);
		
		//Book:
		//    'book' title=STRING 'author=' author=STRING 'isbn=' isbn=STRING
		//    ('borrowedBy=' borrower=[User])?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'book' title=STRING 'author=' author=STRING 'isbn=' isbn=STRING
		//('borrowedBy=' borrower=[User])?
		public Group getGroup() { return cGroup; }
		
		//'book'
		public Keyword getBookKeyword_0() { return cBookKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'author='
		public Keyword getAuthorKeyword_2() { return cAuthorKeyword_2; }
		
		//author=STRING
		public Assignment getAuthorAssignment_3() { return cAuthorAssignment_3; }
		
		//STRING
		public RuleCall getAuthorSTRINGTerminalRuleCall_3_0() { return cAuthorSTRINGTerminalRuleCall_3_0; }
		
		//'isbn='
		public Keyword getIsbnKeyword_4() { return cIsbnKeyword_4; }
		
		//isbn=STRING
		public Assignment getIsbnAssignment_5() { return cIsbnAssignment_5; }
		
		//STRING
		public RuleCall getIsbnSTRINGTerminalRuleCall_5_0() { return cIsbnSTRINGTerminalRuleCall_5_0; }
		
		//('borrowedBy=' borrower=[User])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'borrowedBy='
		public Keyword getBorrowedByKeyword_6_0() { return cBorrowedByKeyword_6_0; }
		
		//borrower=[User]
		public Assignment getBorrowerAssignment_6_1() { return cBorrowerAssignment_6_1; }
		
		//[User]
		public CrossReference getBorrowerUserCrossReference_6_1_0() { return cBorrowerUserCrossReference_6_1_0; }
		
		//ID
		public RuleCall getBorrowerUserIDTerminalRuleCall_6_1_0_1() { return cBorrowerUserIDTerminalRuleCall_6_1_0_1; }
	}
	public class ReservationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Reservation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReserveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cUserKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cUserAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cUserUserCrossReference_2_0 = (CrossReference)cUserAssignment_2.eContents().get(0);
		private final RuleCall cUserUserIDTerminalRuleCall_2_0_1 = (RuleCall)cUserUserCrossReference_2_0.eContents().get(1);
		private final Keyword cBookKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBookAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cBookBookCrossReference_4_0 = (CrossReference)cBookAssignment_4.eContents().get(0);
		private final RuleCall cBookBookIDTerminalRuleCall_4_0_1 = (RuleCall)cBookBookCrossReference_4_0.eContents().get(1);
		private final Keyword cFromKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFromAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFromDATETerminalRuleCall_6_0 = (RuleCall)cFromAssignment_6.eContents().get(0);
		private final Keyword cToKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cToAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cToDATETerminalRuleCall_8_0 = (RuleCall)cToAssignment_8.eContents().get(0);
		
		//Reservation:
		//    'reserve' 'user=' user=[User] 'book=' book=[Book]
		//    'from=' from=DATE 'to=' to=DATE;
		@Override public ParserRule getRule() { return rule; }
		
		//'reserve' 'user=' user=[User] 'book=' book=[Book]
		//'from=' from=DATE 'to=' to=DATE
		public Group getGroup() { return cGroup; }
		
		//'reserve'
		public Keyword getReserveKeyword_0() { return cReserveKeyword_0; }
		
		//'user='
		public Keyword getUserKeyword_1() { return cUserKeyword_1; }
		
		//user=[User]
		public Assignment getUserAssignment_2() { return cUserAssignment_2; }
		
		//[User]
		public CrossReference getUserUserCrossReference_2_0() { return cUserUserCrossReference_2_0; }
		
		//ID
		public RuleCall getUserUserIDTerminalRuleCall_2_0_1() { return cUserUserIDTerminalRuleCall_2_0_1; }
		
		//'book='
		public Keyword getBookKeyword_3() { return cBookKeyword_3; }
		
		//book=[Book]
		public Assignment getBookAssignment_4() { return cBookAssignment_4; }
		
		//[Book]
		public CrossReference getBookBookCrossReference_4_0() { return cBookBookCrossReference_4_0; }
		
		//ID
		public RuleCall getBookBookIDTerminalRuleCall_4_0_1() { return cBookBookIDTerminalRuleCall_4_0_1; }
		
		//'from='
		public Keyword getFromKeyword_5() { return cFromKeyword_5; }
		
		//from=DATE
		public Assignment getFromAssignment_6() { return cFromAssignment_6; }
		
		//DATE
		public RuleCall getFromDATETerminalRuleCall_6_0() { return cFromDATETerminalRuleCall_6_0; }
		
		//'to='
		public Keyword getToKeyword_7() { return cToKeyword_7; }
		
		//to=DATE
		public Assignment getToAssignment_8() { return cToAssignment_8; }
		
		//DATE
		public RuleCall getToDATETerminalRuleCall_8_0() { return cToDATETerminalRuleCall_8_0; }
	}
	
	
	private final ModelElements pModel;
	private final LibraryElements pLibrary;
	private final UserElements pUser;
	private final BookElements pBook;
	private final ReservationElements pReservation;
	private final TerminalRule tDATE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pLibrary = new LibraryElements();
		this.pUser = new UserElements();
		this.pBook = new BookElements();
		this.pReservation = new ReservationElements();
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DATE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    libraries+=Library*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Library:
	//    'library' name=ID '{'
	//        users+=User*
	//        books+=Book*
	//        reservations+=Reservation*
	//    '}';
	public LibraryElements getLibraryAccess() {
		return pLibrary;
	}
	
	public ParserRule getLibraryRule() {
		return getLibraryAccess().getRule();
	}
	
	//User:
	//    'user' name=ID 'email=' email=STRING
	//    ('books=' '{' ownedBooks+=[Book] (',' ownedBooks+=[Book])* '}')?
	//    ('currentReservation=' currentReservation=[Reservation])?
	//;
	public UserElements getUserAccess() {
		return pUser;
	}
	
	public ParserRule getUserRule() {
		return getUserAccess().getRule();
	}
	
	//Book:
	//    'book' title=STRING 'author=' author=STRING 'isbn=' isbn=STRING
	//    ('borrowedBy=' borrower=[User])?
	//;
	public BookElements getBookAccess() {
		return pBook;
	}
	
	public ParserRule getBookRule() {
		return getBookAccess().getRule();
	}
	
	//Reservation:
	//    'reserve' 'user=' user=[User] 'book=' book=[Book]
	//    'from=' from=DATE 'to=' to=DATE;
	public ReservationElements getReservationAccess() {
		return pReservation;
	}
	
	public ParserRule getReservationRule() {
		return getReservationAccess().getRule();
	}
	
	//terminal DATE returns ecore::EDate:
	//    '"' ('0'..'9')+ '-' ('0'..'9')+ '-' ('0'..'9')+ '"';
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
