/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.mydsl.myDsl.Book;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Reservation;
import org.xtext.example.mydsl.myDsl.User;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserImpl#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserImpl#getOwnedBooks <em>Owned Books</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UserImpl#getCurrentReservation <em>Current Reservation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UserImpl extends MinimalEObjectImpl.Container implements User
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected static final String EMAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected String email = EMAIL_EDEFAULT;

  /**
   * The cached value of the '{@link #getOwnedBooks() <em>Owned Books</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedBooks()
   * @generated
   * @ordered
   */
  protected EList<Book> ownedBooks;

  /**
   * The cached value of the '{@link #getCurrentReservation() <em>Current Reservation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCurrentReservation()
   * @generated
   * @ordered
   */
  protected Reservation currentReservation;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UserImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.USER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEmail()
  {
    return email;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEmail(String newEmail)
  {
    String oldEmail = email;
    email = newEmail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER__EMAIL, oldEmail, email));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Book> getOwnedBooks()
  {
    if (ownedBooks == null)
    {
      ownedBooks = new EObjectResolvingEList<Book>(Book.class, this, MyDslPackage.USER__OWNED_BOOKS);
    }
    return ownedBooks;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reservation getCurrentReservation()
  {
    if (currentReservation != null && currentReservation.eIsProxy())
    {
      InternalEObject oldCurrentReservation = (InternalEObject)currentReservation;
      currentReservation = (Reservation)eResolveProxy(oldCurrentReservation);
      if (currentReservation != oldCurrentReservation)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.USER__CURRENT_RESERVATION, oldCurrentReservation, currentReservation));
      }
    }
    return currentReservation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Reservation basicGetCurrentReservation()
  {
    return currentReservation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCurrentReservation(Reservation newCurrentReservation)
  {
    Reservation oldCurrentReservation = currentReservation;
    currentReservation = newCurrentReservation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER__CURRENT_RESERVATION, oldCurrentReservation, currentReservation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.USER__NAME:
        return getName();
      case MyDslPackage.USER__EMAIL:
        return getEmail();
      case MyDslPackage.USER__OWNED_BOOKS:
        return getOwnedBooks();
      case MyDslPackage.USER__CURRENT_RESERVATION:
        if (resolve) return getCurrentReservation();
        return basicGetCurrentReservation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.USER__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.USER__EMAIL:
        setEmail((String)newValue);
        return;
      case MyDslPackage.USER__OWNED_BOOKS:
        getOwnedBooks().clear();
        getOwnedBooks().addAll((Collection<? extends Book>)newValue);
        return;
      case MyDslPackage.USER__CURRENT_RESERVATION:
        setCurrentReservation((Reservation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.USER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.USER__EMAIL:
        setEmail(EMAIL_EDEFAULT);
        return;
      case MyDslPackage.USER__OWNED_BOOKS:
        getOwnedBooks().clear();
        return;
      case MyDslPackage.USER__CURRENT_RESERVATION:
        setCurrentReservation((Reservation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.USER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.USER__EMAIL:
        return EMAIL_EDEFAULT == null ? email != null : !EMAIL_EDEFAULT.equals(email);
      case MyDslPackage.USER__OWNED_BOOKS:
        return ownedBooks != null && !ownedBooks.isEmpty();
      case MyDslPackage.USER__CURRENT_RESERVATION:
        return currentReservation != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", email: ");
    result.append(email);
    result.append(')');
    return result.toString();
  }

} //UserImpl
