/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getLibraryAccess().getGroup(), "rule__Library__Group__0");
			builder.put(grammarAccess.getUserAccess().getGroup(), "rule__User__Group__0");
			builder.put(grammarAccess.getUserAccess().getGroup_4(), "rule__User__Group_4__0");
			builder.put(grammarAccess.getUserAccess().getGroup_4_3(), "rule__User__Group_4_3__0");
			builder.put(grammarAccess.getUserAccess().getGroup_5(), "rule__User__Group_5__0");
			builder.put(grammarAccess.getBookAccess().getGroup(), "rule__Book__Group__0");
			builder.put(grammarAccess.getBookAccess().getGroup_6(), "rule__Book__Group_6__0");
			builder.put(grammarAccess.getReservationAccess().getGroup(), "rule__Reservation__Group__0");
			builder.put(grammarAccess.getModelAccess().getLibrariesAssignment(), "rule__Model__LibrariesAssignment");
			builder.put(grammarAccess.getLibraryAccess().getNameAssignment_1(), "rule__Library__NameAssignment_1");
			builder.put(grammarAccess.getLibraryAccess().getUsersAssignment_3(), "rule__Library__UsersAssignment_3");
			builder.put(grammarAccess.getLibraryAccess().getBooksAssignment_4(), "rule__Library__BooksAssignment_4");
			builder.put(grammarAccess.getLibraryAccess().getReservationsAssignment_5(), "rule__Library__ReservationsAssignment_5");
			builder.put(grammarAccess.getUserAccess().getNameAssignment_1(), "rule__User__NameAssignment_1");
			builder.put(grammarAccess.getUserAccess().getEmailAssignment_3(), "rule__User__EmailAssignment_3");
			builder.put(grammarAccess.getUserAccess().getOwnedBooksAssignment_4_2(), "rule__User__OwnedBooksAssignment_4_2");
			builder.put(grammarAccess.getUserAccess().getOwnedBooksAssignment_4_3_1(), "rule__User__OwnedBooksAssignment_4_3_1");
			builder.put(grammarAccess.getUserAccess().getCurrentReservationAssignment_5_1(), "rule__User__CurrentReservationAssignment_5_1");
			builder.put(grammarAccess.getBookAccess().getTitleAssignment_1(), "rule__Book__TitleAssignment_1");
			builder.put(grammarAccess.getBookAccess().getAuthorAssignment_3(), "rule__Book__AuthorAssignment_3");
			builder.put(grammarAccess.getBookAccess().getIsbnAssignment_5(), "rule__Book__IsbnAssignment_5");
			builder.put(grammarAccess.getBookAccess().getBorrowerAssignment_6_1(), "rule__Book__BorrowerAssignment_6_1");
			builder.put(grammarAccess.getReservationAccess().getUserAssignment_2(), "rule__Reservation__UserAssignment_2");
			builder.put(grammarAccess.getReservationAccess().getBookAssignment_4(), "rule__Reservation__BookAssignment_4");
			builder.put(grammarAccess.getReservationAccess().getFromAssignment_6(), "rule__Reservation__FromAssignment_6");
			builder.put(grammarAccess.getReservationAccess().getToAssignment_8(), "rule__Reservation__ToAssignment_8");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
