/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Library</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Library#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Library#getUsers <em>Users</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Library#getBooks <em>Books</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Library#getReservations <em>Reservations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLibrary()
 * @model
 * @generated
 */
public interface Library extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLibrary_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Library#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Users</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.User}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Users</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLibrary_Users()
   * @model containment="true"
   * @generated
   */
  EList<User> getUsers();

  /**
   * Returns the value of the '<em><b>Books</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Book}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Books</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLibrary_Books()
   * @model containment="true"
   * @generated
   */
  EList<Book> getBooks();

  /**
   * Returns the value of the '<em><b>Reservations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Reservation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reservations</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLibrary_Reservations()
   * @model containment="true"
   * @generated
   */
  EList<Reservation> getReservations();

} // Library
