/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import java.util.Date;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reservation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Reservation#getUser <em>User</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Reservation#getBook <em>Book</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Reservation#getFrom <em>From</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Reservation#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReservation()
 * @model
 * @generated
 */
public interface Reservation extends EObject
{
  /**
   * Returns the value of the '<em><b>User</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>User</em>' reference.
   * @see #setUser(User)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReservation_User()
   * @model
   * @generated
   */
  User getUser();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Reservation#getUser <em>User</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>User</em>' reference.
   * @see #getUser()
   * @generated
   */
  void setUser(User value);

  /**
   * Returns the value of the '<em><b>Book</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Book</em>' reference.
   * @see #setBook(Book)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReservation_Book()
   * @model
   * @generated
   */
  Book getBook();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Reservation#getBook <em>Book</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Book</em>' reference.
   * @see #getBook()
   * @generated
   */
  void setBook(Book value);

  /**
   * Returns the value of the '<em><b>From</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' attribute.
   * @see #setFrom(Date)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReservation_From()
   * @model
   * @generated
   */
  Date getFrom();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Reservation#getFrom <em>From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' attribute.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Date value);

  /**
   * Returns the value of the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' attribute.
   * @see #setTo(Date)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getReservation_To()
   * @model
   * @generated
   */
  Date getTo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Reservation#getTo <em>To</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' attribute.
   * @see #getTo()
   * @generated
   */
  void setTo(Date value);

} // Reservation
