/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.User#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.User#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.User#getOwnedBooks <em>Owned Books</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.User#getCurrentReservation <em>Current Reservation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUser()
 * @model
 * @generated
 */
public interface User extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUser_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.User#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUser_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.User#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Owned Books</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Book}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Books</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUser_OwnedBooks()
   * @model
   * @generated
   */
  EList<Book> getOwnedBooks();

  /**
   * Returns the value of the '<em><b>Current Reservation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current Reservation</em>' reference.
   * @see #setCurrentReservation(Reservation)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUser_CurrentReservation()
   * @model
   * @generated
   */
  Reservation getCurrentReservation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.User#getCurrentReservation <em>Current Reservation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current Reservation</em>' reference.
   * @see #getCurrentReservation()
   * @generated
   */
  void setCurrentReservation(Reservation value);

} // User
